import {
  categoryCreate,
  categoryList,
  categoryRemove,
  categoryUpdate,
  create as createCatalogItem,
  get as getCatalogItem,
  imageCreate,
  imageRemove,
  list as listCatalogItems,
  listForKiosk as listCatalogItemsForKiosk,
  remove as removeCatalogItem,
  stockAdjust,
  update as updateCatalogItem,
  variantCreate,
  variantRemove,
  variantUpdate,
} from './Catalog';
import { tags as classTags, list as listClasses } from './Classes';
import { listActive as listActiveCoupons, list as listCoupons } from './Coupons';
import { earningsChart, financialStats, memberAverageChart, membershipStats } from './Dashboard';
import { list as listEvents } from './Events';
import { addMembership, changeMembership, create as createMember, getHOHForMember, getHOHPaymentMethods, linkFamily, listAllMembershipPlans, listFamily, listMembershipPlans, listMemberTransactions, listPaymentMethods, remove as removeMember, restore as restoreMember, searchHOH, sendConfirmationEmail, unlinkFamily, updateLastAccessed, update as updateMember, updateContactInfo as updateMemberContactInfo, updateMemberType } from './Member';
import { list as listMembers } from './Members';
import { create as createNoteHandler, list as listNotes, remove as removeNoteHandler, update as updateNoteHandler } from './Notes';
import { getTokenizationIframeConfig, processPayment, registerPaymentMethod } from './Payment';
import { chartData as reportChartData, currentValues as reportCurrentValues, insights as reportInsights } from './Reports';
import { cancelSaasSubscription, changeSaasPlan, getCurrentPlan, getSaasBillingHistory, getSaasTokenizationConfig, subscribeToPlan } from './SaasSubscription';
import { create as createTagHandler, listAll as listAllTags, listClassTags, listMembershipTags, remove as removeTagHandler, update as updateTagHandler } from './Tags';
import { get as getTransaction, list as listTransactions } from './Transactions';
import {
  addWaiverToMembership,
  createMergeFieldHandler,
  createSignedWaiverRecord,
  createTemplate as createWaiverTemplate,
  deleteMergeFieldHandler,
  deleteTemplate as deleteWaiverTemplate,
  getSignedWaiver,
  getWaiversForMembership,
  getTemplate as getWaiverTemplate,
  getTemplateVersion as getWaiverTemplateVersion,
  listActiveTemplates as listActiveWaiverTemplates,
  listMemberSignedWaivers,
  listMergeFields,
  listTemplates as listWaiverTemplates,
  listTemplateVersions as listWaiverTemplateVersions,
  removeWaiverFromMembership,
  resolveTemplatePlaceholders,
  setMembershipWaiverAssociations,
  updateMergeFieldHandler,
  updateTemplate as updateWaiverTemplate,
} from './Waivers';

export const router = {
  members: {
    list: listMembers,
  },
  member: {
    create: createMember,
    update: updateMember,
    updateContactInfo: updateMemberContactInfo,
    addMembership,
    changeMembership,
    listMembershipPlans,
    listAllMembershipPlans,
    listPaymentMethods,
    listMemberTransactions,
    remove: removeMember,
    restore: restoreMember,
    updateLastAccessed,
    searchHOH,
    linkFamilyMember: linkFamily,
    listFamilyMembers: listFamily,
    getHOHPaymentMethods,
    unlinkFamilyMember: unlinkFamily,
    getHOHForMember,
    sendConfirmationEmail,
    updateMemberType,
  },
  classes: {
    list: listClasses,
    tags: classTags,
  },
  events: {
    list: listEvents,
  },
  tags: {
    listAll: listAllTags,
    listClassTags,
    listMembershipTags,
    create: createTagHandler,
    update: updateTagHandler,
    remove: removeTagHandler,
  },
  transactions: {
    list: listTransactions,
    get: getTransaction,
  },
  payment: {
    process: processPayment,
    registerPaymentMethod,
    getTokenizationConfig: getTokenizationIframeConfig,
  },
  dashboard: {
    membershipStats,
    financialStats,
    memberAverageChart,
    earningsChart,
  },
  reports: {
    currentValues: reportCurrentValues,
    chartData: reportChartData,
    insights: reportInsights,
  },
  coupons: {
    list: listCoupons,
    listActive: listActiveCoupons,
  },
  notes: {
    list: listNotes,
    create: createNoteHandler,
    update: updateNoteHandler,
    remove: removeNoteHandler,
  },
  catalog: {
    list: listCatalogItems,
    listForKiosk: listCatalogItemsForKiosk,
    get: getCatalogItem,
    create: createCatalogItem,
    update: updateCatalogItem,
    remove: removeCatalogItem,
    variantCreate,
    variantUpdate,
    variantRemove,
    stockAdjust,
    categoryList,
    categoryCreate,
    categoryUpdate,
    categoryRemove,
    imageCreate,
    imageRemove,
  },
  saasSubscription: {
    getCurrentPlan,
    subscribe: subscribeToPlan,
    changePlan: changeSaasPlan,
    cancel: cancelSaasSubscription,
    getBillingHistory: getSaasBillingHistory,
    getTokenizationConfig: getSaasTokenizationConfig,
  },
  waivers: {
    listTemplates: listWaiverTemplates,
    listActiveTemplates: listActiveWaiverTemplates,
    getTemplate: getWaiverTemplate,
    createTemplate: createWaiverTemplate,
    updateTemplate: updateWaiverTemplate,
    deleteTemplate: deleteWaiverTemplate,
    listMemberSignedWaivers,
    getSignedWaiver,
    createSignedWaiver: createSignedWaiverRecord,
    getWaiversForMembership,
    setMembershipWaivers: setMembershipWaiverAssociations,
    addWaiverToMembership,
    removeWaiverFromMembership,
    listTemplateVersions: listWaiverTemplateVersions,
    getTemplateVersion: getWaiverTemplateVersion,
    resolvePlaceholders: resolveTemplatePlaceholders,
    listMergeFields,
    createMergeField: createMergeFieldHandler,
    updateMergeField: updateMergeFieldHandler,
    deleteMergeField: deleteMergeFieldHandler,
  },
};
